// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
  non_camel_case_types,
  unused,
  non_snake_case,
  clippy::needless_return,
  clippy::redundant_closure_call,
  clippy::redundant_closure,
  clippy::useless_conversion,
  clippy::unit_arg,
  clippy::unused_unit,
  clippy::double_parens,
  clippy::let_and_return,
  clippy::too_many_arguments,
  clippy::match_single_binding,
  clippy::clone_on_copy,
  clippy::let_unit_value,
  clippy::deref_addrof,
  clippy::explicit_auto_deref,
  clippy::borrow_deref_ref,
  clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
  default_stream_sink_codec = SseCodec,
  default_rust_opaque = RustOpaqueMoi,
  default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1125004334;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__ffi__api__close_session_impl(
  ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
  rust_vec_len_: i32,
  data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
    flutter_rust_bridge::for_generated::TaskInfo {
      debug_name: "close_session",
      port: None,
      mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
    },
    move || {
      let message = unsafe {
        flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
          ptr_,
          rust_vec_len_,
          data_len_,
        )
      };
      let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
      let api_session_id = <String>::sse_decode(&mut deserializer);
      deserializer.end();
      transform_result_sse::<_, ()>((move || {
        let output_ok = Result::<_, ()>::Ok({
          crate::ffi::api::close_session(api_session_id);
        })?;
        Ok(output_ok)
      })())
    },
  )
}
fn wire__crate__ffi__api__create_session_initiator_impl(
  ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
  rust_vec_len_: i32,
  data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
    flutter_rust_bridge::for_generated::TaskInfo {
      debug_name: "create_session_initiator",
      port: None,
      mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
    },
    move || {
      let message = unsafe {
        flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
          ptr_,
          rust_vec_len_,
          data_len_,
        )
      };
      let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
      let api_identity_bytes_json = <String>::sse_decode(&mut deserializer);
      let api_prekey_bundle_json = <String>::sse_decode(&mut deserializer);
      deserializer.end();
      transform_result_sse::<_, ()>((move || {
        let output_ok = Result::<_, ()>::Ok(crate::ffi::api::create_session_initiator(
          api_identity_bytes_json,
          api_prekey_bundle_json,
        ))?;
        Ok(output_ok)
      })())
    },
  )
}
fn wire__crate__ffi__api__create_session_responder_impl(
  ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
  rust_vec_len_: i32,
  data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
    flutter_rust_bridge::for_generated::TaskInfo {
      debug_name: "create_session_responder",
      port: None,
      mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
    },
    move || {
      let message = unsafe {
        flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
          ptr_,
          rust_vec_len_,
          data_len_,
        )
      };
      let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
      let api_identity_bytes_json = <String>::sse_decode(&mut deserializer);
      let api_signed_prekey_id = <u32>::sse_decode(&mut deserializer);
      let api_one_time_prekey_id = <Option<u32>>::sse_decode(&mut deserializer);
      let api_alice_identity_hex = <String>::sse_decode(&mut deserializer);
      let api_alice_ephemeral_public_key_hex = <String>::sse_decode(&mut deserializer);
      deserializer.end();
      transform_result_sse::<_, ()>((move || {
        let output_ok = Result::<_, ()>::Ok(crate::ffi::api::create_session_responder(
          api_identity_bytes_json,
          api_signed_prekey_id,
          api_one_time_prekey_id,
          api_alice_identity_hex,
          api_alice_ephemeral_public_key_hex,
        ))?;
        Ok(output_ok)
      })())
    },
  )
}
fn wire__crate__ffi__api__decrypt_message_impl(
  ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
  rust_vec_len_: i32,
  data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
    flutter_rust_bridge::for_generated::TaskInfo {
      debug_name: "decrypt_message",
      port: None,
      mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
    },
    move || {
      let message = unsafe {
        flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
          ptr_,
          rust_vec_len_,
          data_len_,
        )
      };
      let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
      let api_session_id = <String>::sse_decode(&mut deserializer);
      let api_envelope_base64 = <String>::sse_decode(&mut deserializer);
      deserializer.end();
      transform_result_sse::<_, ()>((move || {
        let output_ok = Result::<_, ()>::Ok(crate::ffi::api::decrypt_message(
          api_session_id,
          api_envelope_base64,
        ))?;
        Ok(output_ok)
      })())
    },
  )
}
fn wire__crate__ffi__api__encrypt_message_impl(
  ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
  rust_vec_len_: i32,
  data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
    flutter_rust_bridge::for_generated::TaskInfo {
      debug_name: "encrypt_message",
      port: None,
      mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
    },
    move || {
      let message = unsafe {
        flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
          ptr_,
          rust_vec_len_,
          data_len_,
        )
      };
      let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
      let api_session_id = <String>::sse_decode(&mut deserializer);
      let api_plaintext = <Vec<u8>>::sse_decode(&mut deserializer);
      deserializer.end();
      transform_result_sse::<_, ()>((move || {
        let output_ok = Result::<_, ()>::Ok(crate::ffi::api::encrypt_message(
          api_session_id,
          api_plaintext,
        ))?;
        Ok(output_ok)
      })())
    },
  )
}
fn wire__crate__ffi__api__generate_identity_key_pair_impl(
  ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
  rust_vec_len_: i32,
  data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
    flutter_rust_bridge::for_generated::TaskInfo {
      debug_name: "generate_identity_key_pair",
      port: None,
      mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
    },
    move || {
      let message = unsafe {
        flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
          ptr_,
          rust_vec_len_,
          data_len_,
        )
      };
      let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
      deserializer.end();
      transform_result_sse::<_, ()>((move || {
        let output_ok = Result::<_, ()>::Ok(crate::ffi::api::generate_identity_key_pair())?;
        Ok(output_ok)
      })())
    },
  )
}
fn wire__crate__ffi__api__generate_prekey_bundle_impl(
  ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
  rust_vec_len_: i32,
  data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
    flutter_rust_bridge::for_generated::TaskInfo {
      debug_name: "generate_prekey_bundle",
      port: None,
      mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
    },
    move || {
      let message = unsafe {
        flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
          ptr_,
          rust_vec_len_,
          data_len_,
        )
      };
      let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
      let api_identity_bytes_json = <String>::sse_decode(&mut deserializer);
      let api_signed_prekey_id = <u32>::sse_decode(&mut deserializer);
      let api_one_time_prekey_id = <Option<u32>>::sse_decode(&mut deserializer);
      deserializer.end();
      transform_result_sse::<_, ()>((move || {
        let output_ok = Result::<_, ()>::Ok(crate::ffi::api::generate_prekey_bundle(
          api_identity_bytes_json,
          api_signed_prekey_id,
          api_one_time_prekey_id,
        ))?;
        Ok(output_ok)
      })())
    },
  )
}
fn wire__crate__ffi__api__get_public_key_hex_from_json_impl(
  ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
  rust_vec_len_: i32,
  data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
    flutter_rust_bridge::for_generated::TaskInfo {
      debug_name: "get_public_key_hex_from_json",
      port: None,
      mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
    },
    move || {
      let message = unsafe {
        flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
          ptr_,
          rust_vec_len_,
          data_len_,
        )
      };
      let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
      let api_identity_bytes_json = <String>::sse_decode(&mut deserializer);
      deserializer.end();
      transform_result_sse::<_, ()>((move || {
        let output_ok = Result::<_, ()>::Ok(crate::ffi::api::get_public_key_hex_from_json(
          api_identity_bytes_json,
        ))?;
        Ok(output_ok)
      })())
    },
  )
}

// Section: dart2rust

impl SseDecode for String {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
    let mut inner = <Vec<u8>>::sse_decode(deserializer);
    return String::from_utf8(inner).unwrap();
  }
}

impl SseDecode for Vec<u8> {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
    let mut len_ = <i32>::sse_decode(deserializer);
    let mut ans_ = vec![];
    for idx_ in 0..len_ {
      ans_.push(<u8>::sse_decode(deserializer));
    }
    return ans_;
  }
}

impl SseDecode for Option<u32> {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
    if (<bool>::sse_decode(deserializer)) {
      return Some(<u32>::sse_decode(deserializer));
    } else {
      return None;
    }
  }
}

impl SseDecode for u32 {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
    deserializer.cursor.read_u32::<NativeEndian>().unwrap()
  }
}

impl SseDecode for u8 {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
    deserializer.cursor.read_u8().unwrap()
  }
}

impl SseDecode for () {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
    deserializer.cursor.read_i32::<NativeEndian>().unwrap()
  }
}

impl SseDecode for bool {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
    deserializer.cursor.read_u8().unwrap() != 0
  }
}

fn pde_ffi_dispatcher_primary_impl(
  func_id: i32,
  port: flutter_rust_bridge::for_generated::MessagePort,
  ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
  rust_vec_len: i32,
  data_len: i32,
) {
  // Codec=Pde (Serialization + dispatch), see doc to use other codecs
  match func_id {
    _ => unreachable!(),
  }
}

fn pde_ffi_dispatcher_sync_impl(
  func_id: i32,
  ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
  rust_vec_len: i32,
  data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
  // Codec=Pde (Serialization + dispatch), see doc to use other codecs
  match func_id {
    1 => wire__crate__ffi__api__close_session_impl(ptr, rust_vec_len, data_len),
    2 => wire__crate__ffi__api__create_session_initiator_impl(ptr, rust_vec_len, data_len),
    3 => wire__crate__ffi__api__create_session_responder_impl(ptr, rust_vec_len, data_len),
    4 => wire__crate__ffi__api__decrypt_message_impl(ptr, rust_vec_len, data_len),
    5 => wire__crate__ffi__api__encrypt_message_impl(ptr, rust_vec_len, data_len),
    6 => wire__crate__ffi__api__generate_identity_key_pair_impl(ptr, rust_vec_len, data_len),
    7 => wire__crate__ffi__api__generate_prekey_bundle_impl(ptr, rust_vec_len, data_len),
    8 => wire__crate__ffi__api__get_public_key_hex_from_json_impl(ptr, rust_vec_len, data_len),
    _ => unreachable!(),
  }
}

// Section: rust2dart

impl SseEncode for String {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
    <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
  }
}

impl SseEncode for Vec<u8> {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
    <i32>::sse_encode(self.len() as _, serializer);
    for item in self {
      <u8>::sse_encode(item, serializer);
    }
  }
}

impl SseEncode for Option<u32> {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
    <bool>::sse_encode(self.is_some(), serializer);
    if let Some(value) = self {
      <u32>::sse_encode(value, serializer);
    }
  }
}

impl SseEncode for u32 {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
    serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
  }
}

impl SseEncode for u8 {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
    serializer.cursor.write_u8(self).unwrap();
  }
}

impl SseEncode for () {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
    serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
  }
}

impl SseEncode for bool {
  // Codec=Sse (Serialization based), see doc to use other codecs
  fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
    serializer.cursor.write_u8(self as _).unwrap();
  }
}

#[cfg(not(target_family = "wasm"))]
mod io {
  // This file is automatically generated, so please do not edit it.
  // @generated by `flutter_rust_bridge`@ 2.11.1.

  // Section: imports

  use super::*;
  use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
  use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
  use flutter_rust_bridge::{Handler, IntoIntoDart};

  // Section: boilerplate

  flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
  // This file is automatically generated, so please do not edit it.
  // @generated by `flutter_rust_bridge`@ 2.11.1.

  // Section: imports

  use super::*;
  use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
  use flutter_rust_bridge::for_generated::wasm_bindgen;
  use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
  use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
  use flutter_rust_bridge::{Handler, IntoIntoDart};

  // Section: boilerplate

  flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
