// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'ffi/api.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class E2EECore
    extends BaseEntrypoint<E2EECoreApi, E2EECoreApiImpl, E2EECoreWire> {
  @internal
  static final instance = E2EECore._();

  E2EECore._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    E2EECoreApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required E2EECoreApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<E2EECoreApiImpl, E2EECoreWire> get apiImplConstructor =>
      E2EECoreApiImpl.new;

  @override
  WireConstructor<E2EECoreWire> get wireConstructor =>
      E2EECoreWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1125004334;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'e2ee_core',
    ioDirectory: '../../target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class E2EECoreApi extends BaseApi {
  void crateFfiApiCloseSession({required String sessionId});

  String crateFfiApiCreateSessionInitiator(
      {required String identityBytesJson, required String prekeyBundleJson});

  String crateFfiApiCreateSessionResponder(
      {required String identityBytesJson,
      required int signedPrekeyId,
      int? oneTimePrekeyId,
      required String aliceIdentityHex,
      required String aliceEphemeralPublicKeyHex});

  Uint8List crateFfiApiDecryptMessage(
      {required String sessionId, required String envelopeBase64});

  String crateFfiApiEncryptMessage(
      {required String sessionId, required List<int> plaintext});

  String crateFfiApiGenerateIdentityKeyPair();

  String crateFfiApiGeneratePrekeyBundle(
      {required String identityBytesJson,
      required int signedPrekeyId,
      int? oneTimePrekeyId});

  String crateFfiApiGetPublicKeyHexFromJson(
      {required String identityBytesJson});
}

class E2EECoreApiImpl extends E2EECoreApiImplPlatform implements E2EECoreApi {
  E2EECoreApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateFfiApiCloseSession({required String sessionId}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateFfiApiCloseSessionConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiApiCloseSessionConstMeta => const TaskConstMeta(
        debugName: "close_session",
        argNames: ["sessionId"],
      );

  @override
  String crateFfiApiCreateSessionInitiator(
      {required String identityBytesJson, required String prekeyBundleJson}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(identityBytesJson, serializer);
        sse_encode_String(prekeyBundleJson, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateFfiApiCreateSessionInitiatorConstMeta,
      argValues: [identityBytesJson, prekeyBundleJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiApiCreateSessionInitiatorConstMeta =>
      const TaskConstMeta(
        debugName: "create_session_initiator",
        argNames: ["identityBytesJson", "prekeyBundleJson"],
      );

  @override
  String crateFfiApiCreateSessionResponder(
      {required String identityBytesJson,
      required int signedPrekeyId,
      int? oneTimePrekeyId,
      required String aliceIdentityHex,
      required String aliceEphemeralPublicKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(identityBytesJson, serializer);
        sse_encode_u_32(signedPrekeyId, serializer);
        sse_encode_opt_box_autoadd_u_32(oneTimePrekeyId, serializer);
        sse_encode_String(aliceIdentityHex, serializer);
        sse_encode_String(aliceEphemeralPublicKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateFfiApiCreateSessionResponderConstMeta,
      argValues: [
        identityBytesJson,
        signedPrekeyId,
        oneTimePrekeyId,
        aliceIdentityHex,
        aliceEphemeralPublicKeyHex
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiApiCreateSessionResponderConstMeta =>
      const TaskConstMeta(
        debugName: "create_session_responder",
        argNames: [
          "identityBytesJson",
          "signedPrekeyId",
          "oneTimePrekeyId",
          "aliceIdentityHex",
          "aliceEphemeralPublicKeyHex"
        ],
      );

  @override
  Uint8List crateFfiApiDecryptMessage(
      {required String sessionId, required String envelopeBase64}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        sse_encode_String(envelopeBase64, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateFfiApiDecryptMessageConstMeta,
      argValues: [sessionId, envelopeBase64],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiApiDecryptMessageConstMeta => const TaskConstMeta(
        debugName: "decrypt_message",
        argNames: ["sessionId", "envelopeBase64"],
      );

  @override
  String crateFfiApiEncryptMessage(
      {required String sessionId, required List<int> plaintext}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        sse_encode_list_prim_u_8_loose(plaintext, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateFfiApiEncryptMessageConstMeta,
      argValues: [sessionId, plaintext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiApiEncryptMessageConstMeta => const TaskConstMeta(
        debugName: "encrypt_message",
        argNames: ["sessionId", "plaintext"],
      );

  @override
  String crateFfiApiGenerateIdentityKeyPair() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateFfiApiGenerateIdentityKeyPairConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiApiGenerateIdentityKeyPairConstMeta =>
      const TaskConstMeta(
        debugName: "generate_identity_key_pair",
        argNames: [],
      );

  @override
  String crateFfiApiGeneratePrekeyBundle(
      {required String identityBytesJson,
      required int signedPrekeyId,
      int? oneTimePrekeyId}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(identityBytesJson, serializer);
        sse_encode_u_32(signedPrekeyId, serializer);
        sse_encode_opt_box_autoadd_u_32(oneTimePrekeyId, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateFfiApiGeneratePrekeyBundleConstMeta,
      argValues: [identityBytesJson, signedPrekeyId, oneTimePrekeyId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiApiGeneratePrekeyBundleConstMeta =>
      const TaskConstMeta(
        debugName: "generate_prekey_bundle",
        argNames: ["identityBytesJson", "signedPrekeyId", "oneTimePrekeyId"],
      );

  @override
  String crateFfiApiGetPublicKeyHexFromJson(
      {required String identityBytesJson}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(identityBytesJson, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateFfiApiGetPublicKeyHexFromJsonConstMeta,
      argValues: [identityBytesJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateFfiApiGetPublicKeyHexFromJsonConstMeta =>
      const TaskConstMeta(
        debugName: "get_public_key_hex_from_json",
        argNames: ["identityBytesJson"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
