// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            /// Generate a new identity key pair
/// 
/// # Returns
/// IdentityKeyPairBytes serialized as JSON string
String  generateIdentityKeyPair() => E2EECore.instance.api.crateFfiApiGenerateIdentityKeyPair();

/// Get public key hex from IdentityKeyPairBytes JSON
/// 
/// # Arguments
/// * `identity_bytes_json` - JSON string of IdentityKeyPairBytes
/// 
/// # Returns
/// Public key as hex string, or error message if invalid
String  getPublicKeyHexFromJson({required String identityBytesJson }) => E2EECore.instance.api.crateFfiApiGetPublicKeyHexFromJson(identityBytesJson: identityBytesJson);

/// Generate prekey bundle for a user
/// 
/// # Arguments
/// * `identity_bytes_json` - JSON string of IdentityKeyPairBytes
/// * `signed_prekey_id` - ID for the signed prekey
/// * `one_time_prekey_id` - ID for the one-time prekey (optional, use None if not needed)
/// 
/// # Returns
/// PreKeyBundleJSON serialized as JSON string
String  generatePrekeyBundle({required String identityBytesJson , required int signedPrekeyId , int? oneTimePrekeyId }) => E2EECore.instance.api.crateFfiApiGeneratePrekeyBundle(identityBytesJson: identityBytesJson, signedPrekeyId: signedPrekeyId, oneTimePrekeyId: oneTimePrekeyId);

/// Create a session as initiator (Alice)
/// 
/// Initiates X3DH handshake and creates DoubleRatchet session.
/// 
/// # Arguments
/// * `identity_bytes_json` - JSON string of Alice's IdentityKeyPairBytes
/// * `prekey_bundle_json` - JSON string of Bob's PreKeyBundleJSON
/// 
/// # Returns
/// Session ID (UUID string) if successful, or error message
String  createSessionInitiator({required String identityBytesJson , required String prekeyBundleJson }) => E2EECore.instance.api.crateFfiApiCreateSessionInitiator(identityBytesJson: identityBytesJson, prekeyBundleJson: prekeyBundleJson);

/// Create a session as initiator (Alice) and return ephemeral info
/// 
/// Same as `create_session_initiator` but returns a JSON object including
/// Alice's identity public key and the ephemeral public key used in X3DH.
/// 
/// # Arguments
/// * `identity_bytes_json` - JSON string of Alice's IdentityKeyPairBytes
/// * `prekey_bundle_json` - JSON string of Bob's PreKeyBundleJSON
/// 
/// # Returns
/// JSON string: {
///   "session_id": String,
///   "alice_identity_hex": String,
///   "alice_ephemeral_public_key_hex": String
/// }
String  createSessionInitiatorWithEphemeral({required String identityBytesJson , required String prekeyBundleJson }) => E2EECore.instance.api.crateFfiApiCreateSessionInitiatorWithEphemeral(identityBytesJson: identityBytesJson, prekeyBundleJson: prekeyBundleJson);

/// Create a session as responder (Bob)
/// 
/// Responds to X3DH handshake and creates DoubleRatchet session.
/// 
/// # Arguments
/// * `identity_bytes_json` - JSON string of Bob's IdentityKeyPairBytes
/// * `signed_prekey_id` - ID of the signed prekey Bob used
/// * `one_time_prekey_id` - ID of the one-time prekey Bob used (optional)
/// * `alice_identity_hex` - Alice's identity public key (hex)
/// * `alice_ephemeral_public_key_hex` - Alice's ephemeral public key from X3DH (hex)
/// 
/// # Returns
/// Session ID (UUID string) if successful, or error message
String  createSessionResponder({required String identityBytesJson , required int signedPrekeyId , int? oneTimePrekeyId , required String aliceIdentityHex , required String aliceEphemeralPublicKeyHex }) => E2EECore.instance.api.crateFfiApiCreateSessionResponder(identityBytesJson: identityBytesJson, signedPrekeyId: signedPrekeyId, oneTimePrekeyId: oneTimePrekeyId, aliceIdentityHex: aliceIdentityHex, aliceEphemeralPublicKeyHex: aliceEphemeralPublicKeyHex);

/// Encrypt a message using a session
/// 
/// # Arguments
/// * `session_id` - Session ID
/// * `plaintext` - Plaintext message bytes
/// 
/// # Returns
/// Base64-encoded MessageEnvelope if successful, or error message
String  encryptMessage({required String sessionId , required List<int> plaintext }) => E2EECore.instance.api.crateFfiApiEncryptMessage(sessionId: sessionId, plaintext: plaintext);

/// Decrypt a message using a session
/// 
/// # Arguments
/// * `session_id` - Session ID
/// * `envelope_base64` - Base64-encoded MessageEnvelope
/// 
/// # Returns
/// Decrypted plaintext bytes if successful, or error message
Uint8List  decryptMessage({required String sessionId , required String envelopeBase64 }) => E2EECore.instance.api.crateFfiApiDecryptMessage(sessionId: sessionId, envelopeBase64: envelopeBase64);

/// Close a session
/// 
/// # Arguments
/// * `session_id` - Session ID
void  closeSession({required String sessionId }) => E2EECore.instance.api.crateFfiApiCloseSession(sessionId: sessionId);

            
            